### PR TITLE
instead of checking for an exact extension (.h / .cc) only check that it starts with .h / .c

### PR DESCRIPTION
**Pull request by dirk-thomas**
This addresses #79.

### CODE REVIEW

**Comment by dirk-thomas** [comment]
Ping :wink:

**Comment by LukeCz** [comment]
I think .cc is already addressed in the code - _IsSourceExtension() function - and my recent commit addresses .h.
It seems to me this case can be closed.

**Comment by dirk-thomas** [comment]
There are further extensions beyond `c` and `cc` like `cpp` and `cxx`. So I don't think a static list is sufficient for these cases.

**Comment by LukeCz** [comment]
@dirk-thomas I was checking the code and it seems to me that new code compares with the --extensions list instead of ='.cc' so once you pass cxx, cpp and any other that should work.

**Comment by dirk-thomas** [comment]
I am sorry. I didn't know about the recently added `--headers` option. With `--headers` and `--extensions` all use cases of this PR are covered. Closing...

**Comment by dirk-thomas** [comment]
@LukeCz Since you seem to be actively maintaining `cpplint` I want to ask if you would accept PRs for any of the patches we still maintain on-top of upstream?
- https://github.com/ament/ament_lint/commit/49d787a618088b3fd314619d3ba8aa91b7936f59
- https://github.com/ament/ament_lint/commit/b8ab0e6e5ba19dc99ab95b5db3d52a449ee7a2cc
- https://github.com/ament/ament_lint/commit/7f2af60114d1aad63445eb52032fca0db380e042
- https://github.com/ament/ament_lint/commit/1700c7ebc96bf8288f62843e8f9a2a8134c4a71c

For some it would be necessary to add command line options. I just don't want to spend the time to create PRs if they won't be considered anyway.

**Comment by LukeCz** [comment]
@dirk-thomas I'm sorry for the confusion but I do not have wrights to accept. I just posted my PRs for the features that were missing for me. @eglaysher has been active recently merging changes so maybe you could ping him about your changes.

**Pull request closed without merging**
