### PR TITLE
Move codeowners file to github directory

### PR DESCRIPTION
**Pull request by KendallDoesCoding**
GitHub suggests that the CODEOWNERS file be in the .github directory.

### CODE REVIEW

**Comment by Soheilafsha** [comment]
اگر به پروژه کمک میکند انجام دهید

**Comment by KendallDoesCoding** [comment]
> اگر به پروژه کمک میکند انجام دهید

It doesn't help the project that much but it is good as the repo should be formatted as required.

"این کمک زیادی به پروژه نمی کند، اما خوب است زیرا مخزن باید در صورت نیاز فرمت شود."

**Review by devvsakib — APPROVED** [review]

**Review by devvsakib — CHANGES_REQUESTED** [review]
your PR has a conflict. Please resolve the conflict first to get merged

**Comment by KendallDoesCoding** [comment]
> your PR has a conflict. Please resolve the conflict first to get merged

The conflicts cannot be resolved in the web-editor. Can you please help.

**Comment by devvsakib** [comment]
> 
> The conflicts cannot be resolved in the web-editor. Can you please help.

then again make pr or may you didn't push the changes!

**Comment by KendallDoesCoding** [comment]
> > The conflicts cannot be resolved in the web-editor. Can you please help.
> 
> then again make pr or may you didn't push the changes!

Okay, will do that soon!

**Comment by vapier** [comment]
thanks, merged as commit 0ecf8ac022f57291fd6af33b5051972bf50be3e8 now

**Pull request closed without merging**
