### PR TITLE
Add table of contents to the style guide

### PR DESCRIPTION
**Pull request by basavakanaparthi-alation**
Added an index section to the style guide.

### CODE REVIEW

**Comment by basavakanaparthi-alation** [comment]
I signed it!

**Review by devsoitic08 — APPROVED** [review]
Checked all links, it's all good. Very nice PR!

**Comment by basavakanaparthi-alation** [comment]
@devsoitic08 Could you merge this PR?

**Comment by cgay** [comment]
This is great, but I'm afraid it will quickly become out-of-sync with the Google internal version, in which the table of contents is automatically generated via the `[TOC]` markup. Is there no way to auto-generate this in GitHub flavored markdown?

**Comment by basavakanaparthi-alation** [comment]
@cgay Agree that this would be fragile and also hard to main. Unfortunately, there appears to be no way that this can be autogenerated as of now. Another alternative is if to add an automated test that checks if TOC is intact with the body of the doc (but I think it is fragile too)? 

1. https://help.github.com/en/github/building-a-strong-community/editing-wiki-content

> For security and performance reasons, some syntaxes are unsupported.
> - Transclusion
> - Definition lists
> - Indentation
> - Table of contents

2. https://github.com/isaacs/github/issues/215

**Comment by IsaacG** [comment]
Thanks for your pull request!

The latest iteration of the [style guide](http://google.github.io/styleguide/shellguide.html) has a TOC (albeit manually generated and maintained).

**Pull request closed without merging**
