### PR TITLE
Fix typos in the lisp guide

### PR DESCRIPTION
**Pull request by ebzzry**

### CODE REVIEW

**Comment by phoe** [comment]
Is this repository even maintained? This PR has been hanging for almost two years.

**Comment by dimo414** [comment]
Yes, but it's a too many cooks situation, as each guide is owned internally by a different team. I'll try to ping someone.

**Comment by ebzzry** [comment]
Thanks for noticing!

**Comment by phoe** [comment]
Thanks!

**Comment by ebzzry** [comment]
Thanks!

**Pull request merged**
