### PR TITLE
Tidied up the readme slightly for readability

### PR DESCRIPTION
**Pull request by RobertJGabriel**

### CODE REVIEW

**Comment by RobertJGabriel** [comment]
I signed it!

**Review by amomchilov — COMMENTED** [review]
I wanted to make a change like this too. As the number of style guides grew, the paragraph grew more and more unreadable.

Could you rebase and update this, and we can try to put it through?

**Comment by RobertJGabriel** [comment]
@amomchilov Will do it now.

**Comment by vapier** [comment]
thanks for the suggestion.  the latest version uses a list format to make it easier to locate the right language guide.

**Pull request closed without merging**
