### PR TITLE
Add a canonical link to update the URL for the Shell guide

### PR DESCRIPTION
**Pull request by IsaacG**

### CODE REVIEW

**Comment by dimo414** [comment]
LGTM, thanks!

**Comment by dimo414** [comment]
It looks like Google has re-indexed the page, but is still showing it 😞 [This post](https://stackoverflow.com/q/5086894/113632) is far from canonical, but it's possible the Google Crawler doesn't actually handle XSL properly, which would be a bit ironic.

**Comment by IsaacG** [comment]
I wonder if it would handle a <rel=canonical> XML tag...

**Comment by dimo414** [comment]
I'd be a bit surprised if it did, but I'm not sure.

**Pull request merged**
