### PR TITLE
Fixed a typo in pyguide.html

### PR DESCRIPTION
**Pull request by carolynfischer**
Renamed iff to if.

### CODE REVIEW

**Comment by carolynfischer** [comment]
I signed it!

**Comment by carolynfischer** [comment]
Signed it with a different account as well.

**Comment by Stephan202** [comment]
@carolynfischer, I suspect the original author really did mean to say _iff_, meaning "[if and only if](https://en.wikipedia.org/wiki/If_and_only_if)".

**Comment by carolynfischer** [comment]
Fair enough. :)

**Pull request closed without merging**
