### PR TITLE
Delete Code Owners

### PR DESCRIPTION
**Pull request by KingnQueenJJnKJ**
JASON ALAN JAMES

These style guides are copies of Google's internal style guides to
assist developers working on Google owned and originated open source
projects. Changes should be made to the internal style guide first and
only then copied here.

Unsolicited pull requests will not be merged and are usually closed
without comment. If a PR points out a simple mistake — a typo, a broken
link, etc. — then the correction can be made internally and copied here
through the usual process.

Substantive changes to the style rules and suggested new rules should
not be submitted as a PR in this repository. Material changes must be
proposed, discussed, and approved on the internal forums first.

### CODE REVIEW

**Review by crypt096 — APPROVED** [review]

**Review by devvsakib — CHANGES_REQUESTED** [review]
Your PR has a conflict. Please resolve the conflict first to get merged

**Comment by trottiemcqueen** [comment]
@googlebot I signed it!

**Comment by trottiemcqueen** [comment]
I would like to assist please

**Comment by vapier** [comment]
looks like spam

**Pull request closed without merging**
