### PR TITLE
[vimscript] Update name in credits

### PR DESCRIPTION
**Pull request by dbarnett**

### CODE REVIEW

**Comment by dbarnett** [comment]
@artemispax @malcolmr FYI

**Comment by JaphyFan** [comment]
你好，你的邮件已收到,我会尽快回复。祝你工作顺利，生活愉快！

**Comment by artasparks** [comment]
Thanks!

**Comment by dbarnett** [comment]
Okay to apply this one change manually?

I already made the corresponding changes on the internal copy, hoping to manually apply them here for now, and in parallel work on setting up tooling to automatically sync changes from Google internal copy to here.

**Pull request merged**
