### PR TITLE
[Fix] Improved Indent testing

### PR DESCRIPTION
**Pull request by leonidasIIV**
Improved indent testing to test for more than 4 leading spaces as well as improved continuation line testing/exceptions.

Added Unit test for valid Boolean Comparators that we consider to be valid line continuations.

### CODE REVIEW

**Comment by kevineddrs** [comment]
How about now?

**Comment by leonidasIIV** [comment]
I authored these commits

**Comment by LukeCz** [comment]
@leonidasIIV  I think you're pulling too much changes, including done by other people (me included). Maybe you could try to rebase to latest version.

**Comment by leonidasIIV** [comment]
@LukeCz Thanks for the heads up, I'll give it a shot. It appears that the new utility I am using is causing me some grief.

**Pull request closed without merging**
