### PR TITLE
Avoid IWYU warnings on other namespaces for <algorithm>.

### PR DESCRIPTION
**Pull request by pkasting**
This is an extension of the logic already used for other STL headers.

### CODE REVIEW

**Review by ibrahimmemonn — APPROVED** [review]

**Comment by pkasting** [comment]
I don't have permission to merge the PR; can you either merge it or grant me write access?

**Comment by ibrahimmemonn** [comment]
> I don't have permission to merge the PR; can you either merge it or grant me write access?

I can't merge :( I don't have access but I'll request for it

**Comment by tkruse** [comment]
Hi, as far as I am aware, google does not accept PRs for cpplint anymore (since the google-internal cpplint supposedly has evolved a lot. However, this MR might be suitable for https://github.com/cpplint/cpplint, the pypi deployed fork which I have been maintaining.

Would this also fix https://github.com/cpplint/cpplint/issues/200 ?

**Comment by pkasting** [comment]
I don't know offhand, but it might. You're welcome to merge this code into your fork if you wish.

**Review by kbakdev — APPROVED** [review]

**Review by devvsakib — APPROVED** [review]

**Comment by pkasting** [comment]
Seems like PRs here will not be merged, so closing.

**Pull request closed without merging**
