### PR TITLE
Add structured binding support from c++17 to cpplint

### PR DESCRIPTION
**Pull request by artditel**
http://en.cppreference.com/w/cpp/language/structured_binding
Allow code like `auto [a, b] = pair;`

### CODE REVIEW

**Comment by artditel** [comment]
I signed it!

**Comment by tkruse** [comment]
Consider submitting the patch to the fork at https://github.com/cpplint/cpplint

**Comment by m-chaturvedi** [comment]
@artditel have we already gotten something similar merged?
https://github.com/google/styleguide/pull/487

**Comment by artditel** [comment]
> @artditel have we already gotten something similar merged?
> #487

Yes, same effect.
I still don't understand why my pull request got ignored :(

**Comment by m-chaturvedi** [comment]
Maybe because you didn't test it manually?

**Comment by artditel** [comment]
Sure I did. This pull request just got ignored by maintainers for no reason

**Comment by m-chaturvedi** [comment]
Haha, I was just joking because the accepted PR didn't have any unit tests and yours did.

**Pull request closed without merging**
