### PR TITLE
pyguide -- Fix broken URL

### PR DESCRIPTION
**Pull request by rayglover-ibm**

### CODE REVIEW

**Comment by rayglover-ibm** [comment]
It's unlikely that CLA will get signed in the next few months. :( Since URLs aren't protected by copyright, I don't see any problem with someone taking this patch and committing it themselves.

**Comment by Foxytine31** [comment]
I signed it

**Review by Foxytine31 — CHANGES_REQUESTED** [review]
I signed it!

**Comment by gpshead** [comment]
Thanks.  fyi - I will be pushing a big update to the python style guide soon as we unfortunately haven't kept up on updates to in here in our external repo for several years and need to fix that. This link will be cleaned up as part of that. :)

**Comment by gpshead** [comment]
fix pushed.

**Pull request closed without merging**
