### PR TITLE
Render python guide from markdown

### LINKED ISSUE #357: README.md should link to pyguide.md & render that as markdown
https://google.github.io/styleguide/ appears to display README.md rendered properly.

But it links to https://google.github.io/styleguide/pyguide.html which is the obsolete python style guide.

If I try to open https://google.github.io/styleguide/pyguide without a file extension it opens the html file.  :(
If I try to open https://google.github.io/styleguide/pyguide.md it displays the raw markdown instead of rendering it. :(

How does github.io even work?

### LINKED ISSUE #381: pyguide HTML was stale for 5 years then suddenly deprecated
So surprise!
https://github.com/google/styleguide/commit/1707ccb7d18e4980870ce0ea6ab3d380f9a36a30

https://google.github.io/styleguide/pyguide.html
>  Revision 2.59 This is an obsolete unmaintained copy of the style guide. Please use pyguide.md instead. 

I know of _tons_ of people/companies that were leveraging this as the law of Python. (or at least a 3rd party reference/supplicant to the PEP)

As per
https://github.com/google/styleguide/commit/1707ccb7d18e4980870ce0ea6ab3d380f9a36a30#commitcomment-29815046

Is it possible to:
 1. completely delete the content (retain the stub landing page for manual user redirect)
   * -- no point in keeping it around if it's been dead for 5 years
 2. someone from Google please do an assessment of "what's changed" over the past 5 years
   * -- compare HTML to MD -- and provide a "1-year-shelf-life" matrix that tries to succinctly describe the major differences so that people can easily consume the new style guide

Would be awesome! Thank you.

### PR DESCRIPTION
**Pull request by sfdye**
Fixes #381 
Fixes #357

It turns out Github pages will automatically render markdown to html. So we just need to delete the old `pyguide.html` and that's it!

See working version on my fork:
https://sfdye.github.io/styleguide/pyguide.html
or
https://sfdye.github.io/styleguide/pyguide

Ref:
https://blog.github.com/2016-12-09-publishing-with-github-pages-now-as-easy-as-1-2-3/

### CODE REVIEW

**Comment by sfdye** [comment]
I signed it!

**Comment by sfdye** [comment]
Seems like \`\`\`python {.good}\`\`\` and \`\`\`python {.bad}\`\`\` are not rendered correctly by Github Pages, and these "classes" don't seem to have any visual effect. Probably need to remove all the {.good} and {.bad} and use \`\`\`python\`\`\` instead?

**Comment by sfdye** [comment]
ping @cclauss @gpshead

**Comment by gpshead** [comment]
Very annoying that github.io rendering differs from the direct github.com source tree rendering.  :(

The ` {.good}` and similar markers are used by our internal rendering css to give a greenish or redish tint to the background colors in those sections.

Removing them would need to be done as part of our copybara config when pushing our source of truth internal md file to this repository.  Doable, but I don't like having to do that.  Just noting this here because me doing that internally appears to be the only remaining blocker to making this change.

**Comment by sfdye** [comment]
@gpshead I agree. I don't like removing the `{.good}` either, probably worth checking with Github why github.com and Github pages treating css in markdown differently. What do you think? But I guess that's probably a jekyll issue.

**Comment by gpshead** [comment]
Okay copybara updated and a version without the {.good} {.bad} markers has been pushed in https://github.com/google/styleguide/commit/5b06d2d794ee09b3aaf9297e61d734e763a07971

**Comment by gpshead** [comment]
i played with various ways to try and recreate our internal red/green tint colorings on the good/bad code blocks but nothing really worked well, doubly so when trying to be compatible with both github markdown (source tree view) and jekyll markdown (pages / github.io) at the same time.  the only way to get that much style control is to give up on markdown entirely and just pre-render things into html.  not worthwhile.  it was merely a nice to have.

i'm going to merge this PR to get rid of the .html file so that github renders the markdown in its place now.  thanks for the suggestions and push! :)

**Comment by sfdye** [comment]
👏

**Pull request merged**
