### PR TITLE
Merge pull request #187 from google/revert-169-gh-pages

### PR DESCRIPTION
**Pull request by Foxytine31**
Revert "Fix the `cpplint.py` `build/endif_comment` check."

### CODE REVIEW

**Comment by Foxytine31** [comment]
Files merged

**Comment by Foxytine31** [comment]
.patch

**Review by ghost — APPROVED** [review]

**Comment by shicks** [comment]
Is this branch still relevant? I don't know what it's all about, but it seems to have already been merged in.  Is there a reason we shouldn't just delete this branch?

**Comment by shicks** [comment]
I'm closing this since it seems like it's just syncing all the changes and hasn't been touched by the original author in 4.5 years.

**Pull request closed without merging**
