### PR TITLE
Update language to comply with Android's inclusive language guidance

### PR DESCRIPTION
**Pull request by allight**
See https://source.android.com/setup/contribute/respectful-code for
reference

cpplint.py is copied into AOSP from this github version so update it
here first.

Bug: 161896447
Test: None (comments only)

### CODE REVIEW

**Comment by allight** [comment]
@tituswinters @markmentovai PTAL

**Comment by allight** [comment]
@vapier PTAL

**Comment by gpshead** [comment]
Do realize that Google has been negligent on maintaining cpplint as found in this repository.  A community maintained fork exists in https://github.com/cpplint/cpplint.

**Comment by allight** [comment]
@gpshead do you suggest we switch over to that version?

**Pull request merged**
