### PR TITLE
Back to top button

### PR DESCRIPTION
**Pull request by JackZeled0n**
Add back to top into htmlcss guide file

### CODE REVIEW

**Comment by JackZeled0n** [comment]
@googlebot I signed it!

**Comment by tonyruscoe** [comment]
Thanks for the suggestion, but I’m unfortunately unable to accept this pull request because the markup is automatically generated from a shared template we maintain internally.

**Comment by JackZeled0n** [comment]
Is there any way to help you with maintenance?

**Comment by tonyruscoe** [comment]
Not with the markup used by the style guides, but thanks for showing an interest!

**Pull request closed without merging**
